# Generated by Django 2.2 on 2019-04-12 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('titulo', models.CharField(max_length=200)),
                ('capa', models.ImageField(upload_to='img/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
                ('paginas', models.DecimalField(decimal_places=0, max_digits=7)),
                ('editora', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200)),
                ('serie', models.CharField(max_length=200)),
                ('tema', models.CharField(max_length=200)),
                ('faixaetaria', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sinopse', models.TextField()),
                ('ilustracao', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('disponivel', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('idpessoa', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('datanascimento', models.DateField()),
                ('endereco', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotecaeulina.Pessoa')),
                ('ano', models.IntegerField()),
                ('turma', models.CharField(max_length=1)),
                ('turno', models.CharField(choices=[('matutino', 'matutino'), ('vespertino', 'vespertino')], max_length=50)),
                ('nomeresponsavel', models.CharField(max_length=50)),
            ],
            bases=('bibliotecaeulina.pessoa',),
        ),
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotecaeulina.Pessoa')),
                ('alunos', models.TextField()),
            ],
            bases=('bibliotecaeulina.pessoa',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotecaeulina.Pessoa')),
                ('matricula', models.IntegerField()),
                ('turma', models.CharField(max_length=1)),
                ('turno', models.CharField(choices=[('matutino', 'matutino'), ('vespertino', 'vespertino')], max_length=20)),
                ('funcao', models.CharField(max_length=15)),
            ],
            bases=('bibliotecaeulina.pessoa',),
        ),
    ]
