# Generated by Django 2.2 on 2019-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaeulina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.IntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nomeresponsavel',
            field=models.CharField(max_length=50, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(max_length=1, verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turno',
            field=models.CharField(choices=[('matutino', 'matutino'), ('vespertino', 'vespertino')], max_length=50, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='alunos',
            field=models.TextField(verbose_name='Alunos'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='disponivel',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=5, verbose_name='Disponível para Empréstimo'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(max_length=200, verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='faixaetaria',
            field=models.IntegerField(verbose_name='Faixa Etária'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ilustracao',
            field=models.CharField(max_length=200, verbose_name='Ilustração'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=200, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='serie',
            field=models.CharField(max_length=200, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(verbose_name='Sinópse'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(max_length=50, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(max_length=500, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='idpessoa',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=15, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='funcao',
            field=models.CharField(max_length=15, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.IntegerField(verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='turma',
            field=models.CharField(max_length=1, verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='turno',
            field=models.CharField(choices=[('matutino', 'matutino'), ('vespertino', 'vespertino')], max_length=20, verbose_name='Turno'),
        ),
    ]
