# Generated by Django 2.2 on 2019-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaeulina', '0002_auto_20190415_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='datanascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
